name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t flood-impact-assessment .

      - name: test
        run: docker run -v $PWD/data:/data --env PYTHONUNBUFFERED=1 --env DTM_RESOLUTION=5 --env THRESHOLD=0.01 --name flood-impact-assessment flood-impact-assessment
